CREATE DATABASE IF NOT EXISTS glance;
GRANT ALL PRIVILEGES ON glance.* TO glance@'localhost' IDENTIFIED BY 'ADMPWD';
GRANT ALL PRIVILEGES ON glance.* TO glance@'%' IDENTIFIED BY 'ADMPWD';
FLUSH PRIVILEGES;