CREATE DATABASE IF NOT EXISTS neutron_ml2;
GRANT ALL PRIVILEGES ON neutron_ml2.* TO neutron@'localhost' IDENTIFIED BY 'ADMPWD';
GRANT ALL PRIVILEGES ON neutron_ml2.* TO neutron@'%' IDENTIFIED BY 'ADMPWD';
FLUSH PRIVILEGES;